name: finehand_env

dependencies:
  - pip
  - python=3.7
  - matplotlib==3.1.3
  - seaborn==0.10.0
  - numpy==1.18.1
  - tqdm==4.50.2
  - scipy==1.4.1
  - Pillow==7.1.2
  - tensorboard==2.2.1
  - pip:
    - scikit-image==0.18.3
    - torch==1.4.0
    - torchvision==0.5.0
    - opencv_python==4.2.0.34
    - astropy==4.3.1
    - h5py==2.10.0
    - einops
    - sklearn==0.0

